[project]
name = "agentenv"
version = "0.1.0"
description = ""
authors = [
    {name = "KYLN24", email = "hlguo20@fudan.edu.cn"},
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

